### ISSUE TITLE
'Function not resolved in class: no members found error' on R8 build 

### ISSUE THREAD

**Issue by easyhooon** [jisungbin/ComposeInvestigator#155]
compose-runtime-version = above 1.6.4 (compose-bom version = above "2024.03.00")

The following error occurred in the release build, and when R8 retrace was performed, it was confirmed that there was an issue within the Compose runtime.
```
FATAL EXCEPTION: main
Process: com.unifest.android, PID: 30877
qb.i: Function 'onAction' (JVM signature: onAction(Lcom/unifest/android/feature/intro/viewmodel/IntroUiAction;)V) not resolved in class ra.r: no members found
 at r.q0.b(Unknown Source:555)
 at nc.v1.b(Unknown Source:18)
 at nc.j0.r(Unknown Source:7)
 at nc.j0.toString(Unknown Source:2)
 at ec.h.toString(Unknown Source:12)
 at java.lang.String.valueOf(String.java:4092)
...
```
I thought it might be helpful, so I'm attaching the relevant error part from the R8 retrace results.
```
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:109)                                                                                                            at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:35)
at androidx.compose.ui.platform.ComposeView.Content(Unknown Source:428)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(Unknown Source:252)                                                                                                       at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke$bridge(Unknown Source:0)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(Unknown Source:251)                                                                                                       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4$1.invoke$bridge(Unknown Source:0)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:109)                                                                                                            at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(Unknown Source:228)
at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(Unknown Source:186)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(Unknown Source:119)                                                                                                         at androidx.compose.material.ButtonKt$Button$3.invoke$bridge(Unknown Source:0)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(Unknown Source:118)                                                                                                         at androidx.compose.foundation.lazy.grid.LazyGridDslKt$rememberColumnWidthSums$1$1.invoke$bridge(Unknown Source:0)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:109)                                                                                                            at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(Unknown Source:228)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(Unknown Source:110)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Unknown Source:139)                                                                                                          at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke$bridge(Unknown Source:0)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Unknown Source:138)                                                                                                          at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke$bridge(Unknown Source:0)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:109)                                                                                                            at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(Unknown Source:248)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:138)                                                                                                            at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke$bridge(Unknown Source:0)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:123)                                                                                                            at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke$bridge(Unknown Source:0)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:109)                                                                                                            at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:35)
at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(Unknown Source:90)
at androidx.compose.runtime.ComposerImpl.doCompose(Unknown Source:3302)
at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Unknown Source:3235)
at androidx.compose.runtime.CompositionImpl.composeContent(Unknown Source:725)
at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Unknown Source:1071)
at androidx.compose.runtime.CompositionImpl.composeInitial(Unknown Source:633)
at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source:619)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:123)                                                                                                      at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:114)                                                                                                      at androidx.compose.foundation.BorderModifierNode$drawGenericBorder$1.invoke$bridge(Unknown Source:0)
at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:1289)
at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:114)
at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Unknown Source:164)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(Unknown Source:320)
at androidx.lifecycle.LifecycleRegistry.addObserver(Unknown Source:198)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:121)                                                                                                      at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:114)                                                                                                      at androidx.compose.foundation.BorderModifierNode$drawGenericBorder$1.invoke$bridge(Unknown Source:0)
at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:1364)
at android.view.View.dispatchAttachedToWindow(View.java:23215)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3698)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3705)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3883)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3275)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11257)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
at android.view.Choreographer.doFrame(Choreographer.java:1055)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8913)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by jisungbin** [comment]
Thanks for reporting. This will be resolved in a K2 support release.
